apiVersion : apps/v1
kind: Deployment
metadata:
  name: ramrangisettycawebapponkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramrangisettycawebapponkube
  template:
    metadata:
      labels:
        app: ramrangisettycawebapponkube 
    spec:
      containers:
        - name: ramrangisettycawebapponkube 
          image: demoregistryca.azurecr.io/ramrangisettycawebapponkube
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: ramrangisettycawebapponkube
    labels:
      app: ramrangisettycawebapponkube
spec:
    #type: LoadBalancer
    selector: 
      app: ramrangisettycawebapponkube
    ports:
    - port: 80 
      targetPort: 80
